### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by m14055** [SolaceDev/SolaceProductDownload#10]
Solace Product Download
Acceptance of terms: true
Pivnet refresh token provided, discovering latest version from Pivnet

Generating pivnet access token from refresh token
Discovered checksum url https://network.pivotal.io/api/v2/products/solace-pubsub/releases/419157/product_files/438547/download
Successfully downloaded checksum from https://network.pivotal.io/api/v2/products/solace-pubsub/releases/419157/product_files/438547/download

Parsing checksum file
4a64a7ee056bf71bc3c30f9b71be30e26dd8c23911297c64e585e977416a0f29 solace-pubsub-2.3.2-enterprise[release_2.3.2].pivotal

Discovered filepath from checksum

Downloading /products/2.3GA/PCF/Current/2.3.2/solace-pubsub-2.3.2-enterprise[release_2.3.2].pivotal, will be placed in /tmp/build/get
Authenticating as user			maximus
Accepting License Agreement		/Solace-Systems-Software-License-Agreement.pdf
License Agreement as HTML		http://www.solace.com/license-software
Downloading				/Solace-Systems-Software-License-Agreement.pdf
Download OK				Solace-Systems-Software-License-Agreement.pdf
Downloading				/products/2.3GA/PCF/Current/2.3.2/solace-pubsub-2.3.2-enterprise[release_2.3.2].pivotal
curl: (3) bad range in URL position 94:
https://products.solace.com//products/2.3GA/PCF/Current/2.3.2/solace-pubsub-2.3.2-enterprise[release_2.3.2].pivotal

**Comment by PhilippeKhalife** [comment]
This issue was fixed with a new checksum file.
