### ISSUE TITLE
Show progress when Solace is downloading

### ISSUE THREAD

**Issue by m14055** [SolaceDev/SolaceProductDownload#5]
Currently when the Solace tile is downloading, the download message just sits there and it's hard to know how long the download will take. Showing the progress here is important. Other concourse resources like "pivnet" show the progress. 

The code is using "curl -s" which hides any output.

**Comment by PhilippeKhalife** [comment]
Good idea. Will add it soon.

**Comment by PhilippeKhalife** [comment]
Fixed by #6
